### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by sorianocbts** [alipov/edu20-assignment-downloader#4]
Hello, 
I have downloaded and tested your app in Chrome. I changed the urls on the manifest.json file to match my organization's NEOLMS Portal URLs. I got the extension to be enabled when I visit our portal, but I can' download assignments.

Could you please tell me which steps I am missing to get this downloader to work? I would really appreciate it.

**Comment by alipov** [comment]
Hi @sorianocbts, it seems that NEOLMS changed the dropbox_assignment interface a bit - the version I have access to natively supports submissions download with a dedicated "Download submissions" button in `Grades` tab. If you don't see that - then I guess your organization uses a bit older version.

> I got the extension to be enabled when I visit our portal, but I can' download assignments.  

So the "Download All Answers" button is being added to page's DOM, and you can also see it visually, but when you click the button nothing happens?

**Comment by sorianocbts** [comment]
@alipov Thank you for your reply. 
I don't see the button appearing n any of the pages, but I guess this may be due to me using a different NEO LMS version.
